version: '3.7'

# network
networks:
  dbnet:
    driver: bridge

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    environment:
      MARIADB_USER: root
      MARIADB_PASSWORD: pass
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: db_laravel
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - dbnet
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 3000:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_PASSWORD: 'pass'
      UPLOAD_LIMIT: 100M
    restart: unless-stopped
    networks:
      - dbnet
    depends_on:
      - db
  frontend:
    build:
      context: ./vue/
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - node_modules:/app/node_modules
    ports:
      - "3001:80"
  backend:
    build:
      context: ./laravel/
      dockerfile: Dockerfile
      target: production
    image: backend
    restart: unless-stopped
    volumes:
      - ./laravel/:/var/www/html
      - ./laravel/env.dev:/var/www/html/.env
    container_name: backend
    depends_on:
      - db
    ports:
      - "8082:80"
    networks:
      - dbnet
volumes:
  db:
  node_modules: